// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvkjtojvdolcofgkvopx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2a2p0b2p2ZG9sY29mZ2t2b3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzQwODUsImV4cCI6MjA2OTUxMDA4NX0.ed4CDfFYmKrAVwl0fn7A_Jw-pwjgfqBIoh8W3ew0BjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});